// <auto-generated />
namespace AppConsig.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Consignacao_Consignataria_Servico_Servidor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Consignacao_Consignataria_Servico_Servidor));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281158304_Consignacao_Consignataria_Servico_Servidor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
