//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsig.Web.Gestor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alertas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alertas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppConsig.Web.Gestor.Resources.Alertas", typeof(Alertas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso do usuário atualizado.
        /// </summary>
        public static string AcessoAtualizado {
            get {
                return ResourceManager.GetString("AcessoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo acesso de usuário criado.
        /// </summary>
        public static string AcessoCriado {
            get {
                return ResourceManager.GetString("AcessoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso do usuário excluído.
        /// </summary>
        public static string AcessoExcluido {
            get {
                return ResourceManager.GetString("AcessoExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso aos usuários atualizado.
        /// </summary>
        public static string AvisoAtualizado {
            get {
                return ResourceManager.GetString("AvisoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo aviso aos usuários criado.
        /// </summary>
        public static string AvisoCriado {
            get {
                return ResourceManager.GetString("AvisoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso aos usuários excluído.
        /// </summary>
        public static string AvisoExcluido {
            get {
                return ResourceManager.GetString("AvisoExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados atualizados.
        /// </summary>
        public static string ContaAtualizado {
            get {
                return ResourceManager.GetString("ContaAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de usuário atualizado.
        /// </summary>
        public static string PerfilAtualizado {
            get {
                return ResourceManager.GetString("PerfilAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo perdil de usuário criado.
        /// </summary>
        public static string PerfilCriado {
            get {
                return ResourceManager.GetString("PerfilCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de usuário excluído.
        /// </summary>
        public static string PerfilExcluido {
            get {
                return ResourceManager.GetString("PerfilExcluido", resourceCulture);
            }
        }
    }
}
