// <auto-generated />
namespace AppConsig.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201507271110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201507271110));
        
        string IMigrationMetadata.Id
        {
            get { return "201507271408045_20150727 1110"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
