// <auto-generated />
namespace AppConsig.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0957 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0957));
        
        string IMigrationMetadata.Id
        {
            get { return "201508101258219_0957"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
