// <auto-generated />
namespace AppConsig.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_nullable_parent_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_nullable_parent_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201509231911099_add_nullable_parent_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
