// <auto-generated />
namespace AppConsig.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201507221550 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201507221550));
        
        string IMigrationMetadata.Id
        {
            get { return "201507221851276_20150722 1550"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
